import "server-only";
import { sql } from "@/server/db/client";
import { AppInfoService } from "./app-info.service";
import { HealthService } from "./health.service";
import { AuthService } from "./auth.service";
import { JellyfinIntegrationService } from "./jellyfin-integration.service";
import { MediaSyncService } from "./media-sync.service";
import { SeriesProgressService } from "./series-progress.service";
import { UserDirectoryService } from "./user-directory.service";
import { TmdbIntegrationService } from "./tmdb-integration.service";
import { TmdbMetadataService } from "./tmdb-metadata.service";
import { authRepository } from "@/server/db/repositories/auth.repository";
import { jellyfinRepository } from "@/server/db/repositories/jellyfin.repository";
import { mediaSyncRepository } from "@/server/db/repositories/media-sync.repository";
import { tmdbRepository } from "@/server/db/repositories/tmdb.repository";
import { getSecretEncryption } from "@/server/security/secrets";
import { TmdbClient } from "@/server/integrations/tmdb/client";
import { TasteService } from "./taste.service";
import { tasteRepository } from "@/server/db/repositories/taste.repository";
import { UserPreferencesService } from "./user-preferences.service";
import { userPreferencesRepository } from "@/server/db/repositories/user-preferences.repository";
import { RecommendationService } from "./recommendation.service";
import { recommendationRepository } from "@/server/db/repositories/recommendation.repository";
import { aiRepository } from "@/server/db/repositories/ai.repository";
import { AiIntegrationService } from "./ai-integration.service";
import { AiEnhancementService } from "./ai-enhancement.service";
import { OpenAiClient } from "@/server/integrations/ai/openai-client";
import { ArrRepository } from "@/server/db/repositories/arr.repository";
import { ArrClient } from "@/server/integrations/arr/client";
import { ArrIntegrationService } from "./arr-integration.service";
import { acquisitionRepository } from "@/server/db/repositories/acquisition.repository";
import { AcquisitionService } from "./acquisition.service";
import { followRepository } from "@/server/db/repositories/follow.repository";
import { FollowService } from "./follow.service";
import { notificationRepository } from "@/server/db/repositories/notification.repository";
import { NotificationService } from "./notification.service";
import { NtfyClient } from "@/server/integrations/notifications/ntfy-client";
import { m3uEditorRepository } from "@/server/db/repositories/m3u-editor.repository";
import { M3uEditorClient } from "@/server/integrations/m3u-editor/client";
import { M3uEditorIntegrationService } from "./m3u-editor-integration.service";
import { StrmFileService } from "./strm-file.service";
import { StrmImportService } from "./strm-import.service";
import { ActivityService } from "./activity.service";
import { activityRepository } from "@/server/db/repositories/activity.repository";
import { env } from "@/env";

export const appInfoService = new AppInfoService();
export const healthService = new HealthService(async () => {
  await sql`select 1`;
});

let encryption: ReturnType<typeof getSecretEncryption> | undefined;
try {
  encryption = getSecretEncryption();
} catch {
  encryption = undefined;
}

export const jellyfinIntegrationService = new JellyfinIntegrationService(jellyfinRepository, encryption);
export const authService = encryption ? new AuthService(authRepository, jellyfinRepository, encryption) : undefined;
export const mediaSyncService = encryption ? new MediaSyncService(jellyfinRepository, mediaSyncRepository, encryption) : undefined;
export const seriesProgressService = new SeriesProgressService(mediaSyncRepository);
export const userDirectoryService = new UserDirectoryService(jellyfinRepository, mediaSyncRepository);
const tmdbClient = new TmdbClient();
export const tmdbIntegrationService = new TmdbIntegrationService(tmdbRepository, encryption, tmdbClient);
export const m3uEditorIntegrationService = new M3uEditorIntegrationService(m3uEditorRepository, encryption, new M3uEditorClient(), new StrmFileService(env.CUED_STRM_ROOT), () => jellyfinIntegrationService.refreshLibrary());
export const strmImportService = new StrmImportService(m3uEditorRepository, mediaSyncService);
export const tmdbMetadataService = new TmdbMetadataService(tmdbRepository, tmdbIntegrationService, tmdbClient, m3uEditorIntegrationService);
export const tasteService = new TasteService(tasteRepository);
export const userPreferencesService = new UserPreferencesService(userPreferencesRepository);
const openAiClient = new OpenAiClient();
export const aiIntegrationService = new AiIntegrationService(aiRepository, encryption, openAiClient);
export const aiEnhancementService = new AiEnhancementService(aiRepository, aiIntegrationService);
export const recommendationService = new RecommendationService(recommendationRepository, tmdbRepository, tmdbMetadataService, aiEnhancementService);
export const radarrIntegrationService = new ArrIntegrationService(new ArrRepository("radarr"), encryption, new ArrClient("radarr"));
export const sonarrIntegrationService = new ArrIntegrationService(new ArrRepository("sonarr"), encryption, new ArrClient("sonarr"));
export const acquisitionService = new AcquisitionService(acquisitionRepository, radarrIntegrationService, sonarrIntegrationService);
export const followService = new FollowService(followRepository, tmdbMetadataService, acquisitionService);
export const notificationService = new NotificationService(notificationRepository, encryption, new NtfyClient());
export const activityService = new ActivityService(activityRepository);
