import "server-only";
import { and, eq, inArray, like, or, sql } from "drizzle-orm";
import { db } from "@/server/db/client";
import { externalMediaAvailability, integrations, jobRuns, mediaLibraries, userLibraryAccess } from "@/server/db/schema";
import type { M3uEditorTitle } from "@/server/integrations/m3u-editor/provider";

export interface M3uEditorConfiguration extends Record<string, unknown> { username: string; playlistUuid?: string; movieLibraryIds: string[]; seriesLibraryIds: string[]; movieDirectory: string; seriesDirectory: string; refreshJellyfin: boolean }
export class M3uEditorRepository {
  getIntegration() { return db.query.integrations.findFirst({ where: eq(integrations.provider, "m3u-editor") }); }
  getLibraries() { return db.select({ id: mediaLibraries.id, name: mediaLibraries.name, collectionType: mediaLibraries.collectionType }).from(mediaLibraries).where(eq(mediaLibraries.selected, true)); }
  async save(input: { baseUrl: string; encryptedPassword: string; configuration: M3uEditorConfiguration }) { const now = new Date(); const [row] = await db.insert(integrations).values({ provider: "m3u-editor", baseUrl: input.baseUrl, encryptedApiKey: input.encryptedPassword, serverName: "M3U Editor", status: "healthy", lastCheckedAt: now, configuration: input.configuration, updatedAt: now }).onConflictDoUpdate({ target: integrations.provider, set: { baseUrl: input.baseUrl, encryptedApiKey: input.encryptedPassword, configuration: input.configuration, status: "healthy", lastError: null, consecutiveFailures: 0, failureStartedAt: null, lastCheckedAt: now, updatedAt: now } }).returning(); return row!; }
  async setHealth(id: string, status: "healthy" | "degraded", error?: string) { const now = new Date(); await db.update(integrations).set(status === "healthy" ? { status, lastCheckedAt: now, lastError: null, consecutiveFailures: 0, failureStartedAt: null, updatedAt: now } : { status, lastCheckedAt: now, lastError: error ?? null, consecutiveFailures: sql`${integrations.consecutiveFailures} + 1`, failureStartedAt: sql`coalesce(${integrations.failureStartedAt}, ${now})`, updatedAt: now }).where(eq(integrations.id, id)); }
  async replaceAvailability(integrationId: string, titles: M3uEditorTitle[]) { await db.transaction(async (tx) => { await tx.delete(externalMediaAvailability).where(eq(externalMediaAvailability.integrationId, integrationId)); const batchSize = 500; for (let offset = 0; offset < titles.length; offset += batchSize) { const batch = titles.slice(offset, offset + batchSize); await tx.insert(externalMediaAvailability).values(batch.map((title) => ({ integrationId, mediaType: title.type, tmdbId: title.tmdbId, externalId: title.externalId, title: title.title, groupName: title.groupName, containerExtension: title.containerExtension }))).onConflictDoNothing(); } }); }
  async getAvailable(userId: string, titles: Array<{ id: number; type: "movie" | "series" }>) { const integration = await this.getIntegration(); if (!integration) return new Set<string>(); const config = integration.configuration as unknown as M3uEditorConfiguration; const libraryIds = [...new Set([...(config.movieLibraryIds ?? []), ...(config.seriesLibraryIds ?? [])])]; if (!libraryIds.length) return new Set<string>(); const accessRows = await db.select({ libraryId: userLibraryAccess.libraryId }).from(userLibraryAccess).where(and(eq(userLibraryAccess.userId, userId), eq(userLibraryAccess.accessible, true), inArray(userLibraryAccess.libraryId, libraryIds))); const access = new Set(accessRows.map((row) => row.libraryId)); const movieIds = (config.movieLibraryIds ?? []).some((id) => access.has(id)) ? titles.filter((item) => item.type === "movie").map((item) => item.id) : []; const seriesIds = (config.seriesLibraryIds ?? []).some((id) => access.has(id)) ? titles.filter((item) => item.type === "series").map((item) => item.id) : []; if (!movieIds.length && !seriesIds.length) return new Set<string>(); const scope = or(...(movieIds.length ? [and(eq(externalMediaAvailability.mediaType, "movie"), inArray(externalMediaAvailability.tmdbId, movieIds))] : []), ...(seriesIds.length ? [and(eq(externalMediaAvailability.mediaType, "series"), inArray(externalMediaAvailability.tmdbId, seriesIds))] : [])); const rows = await db.select({ type: externalMediaAvailability.mediaType, tmdbId: externalMediaAvailability.tmdbId }).from(externalMediaAvailability).where(and(eq(externalMediaAvailability.integrationId, integration.id), scope)); return new Set(rows.map((row) => `${row.type}:${row.tmdbId}`)); }
  counts(integrationId: string) { return db.select({ type: externalMediaAvailability.mediaType, count: sql<number>`count(*)::int` }).from(externalMediaAvailability).where(eq(externalMediaAvailability.integrationId, integrationId)).groupBy(externalMediaAvailability.mediaType); }
  async getSources(userId: string, type: "movie" | "series", tmdbId: number) { const context = await this.getAccessContext(userId, type); if (!context) return []; return db.select({ id: externalMediaAvailability.id, title: externalMediaAvailability.title, groupName: externalMediaAvailability.groupName }).from(externalMediaAvailability).where(and(eq(externalMediaAvailability.integrationId, context.integration.id), eq(externalMediaAvailability.mediaType, type), eq(externalMediaAvailability.tmdbId, tmdbId))).orderBy(externalMediaAvailability.groupName, externalMediaAvailability.title); }
  async getRequestTarget(userId: string, type: "movie" | "series", tmdbId: number, sourceId?: string) { const context = await this.getAccessContext(userId, type); if (!context) return undefined; const conditions = [eq(externalMediaAvailability.integrationId, context.integration.id), eq(externalMediaAvailability.mediaType, type), eq(externalMediaAvailability.tmdbId, tmdbId)]; if (sourceId) conditions.push(eq(externalMediaAvailability.id, sourceId)); const [title] = await db.select().from(externalMediaAvailability).where(and(...conditions)).limit(1); return title ? { ...context, title } : undefined; }
  async getAccessibleMappedLibraries(userId: string) { const integration = await this.getIntegration(); if (!integration) return { movie: new Set<string>(), series: new Set<string>() }; const config = integration.configuration as unknown as M3uEditorConfiguration; const all = [...new Set([...(config.movieLibraryIds ?? []), ...(config.seriesLibraryIds ?? [])])]; if (!all.length) return { movie: new Set<string>(), series: new Set<string>() }; const rows = await db.select({ id: userLibraryAccess.libraryId }).from(userLibraryAccess).where(and(eq(userLibraryAccess.userId, userId), eq(userLibraryAccess.accessible, true), inArray(userLibraryAccess.libraryId, all))); const accessible = new Set(rows.map((row) => row.id)); return { movie: new Set((config.movieLibraryIds ?? []).filter((id) => accessible.has(id))), series: new Set((config.seriesLibraryIds ?? []).filter((id) => accessible.has(id))) }; }
  async enqueueJellyfinImport(type: "movie" | "series", tmdbId: number) { const jobName = importJobName(type, tmdbId); const existing = await db.query.jobRuns.findFirst({ where: and(eq(jobRuns.jobName, jobName), eq(jobRuns.status, "pending")) }); if (!existing) await db.insert(jobRuns).values({ jobName, status: "pending" }); }
  getPendingJellyfinImports() { return db.query.jobRuns.findMany({ where: and(like(jobRuns.jobName, "strm-jellyfin-import:%"), eq(jobRuns.status, "pending")), orderBy: (job, { asc }) => asc(job.startedAt), limit: 5 }); }
  async getPendingTitles(titles: Array<{ id: number; type: "movie" | "series" }>) { if (!titles.length) return new Set<string>(); const names = titles.map((title) => importJobName(title.type, title.id)); const rows = await db.select({ jobName: jobRuns.jobName }).from(jobRuns).where(and(eq(jobRuns.status, "pending"), inArray(jobRuns.jobName, names))); return new Set(rows.map((row) => row.jobName.replace("strm-jellyfin-import:", ""))); }
  completeJellyfinImport(id: number) { return db.update(jobRuns).set({ status: "completed", finishedAt: new Date(), error: null }).where(eq(jobRuns.id, id)); }
  failJellyfinImport(id: number, error: string) { return db.update(jobRuns).set({ status: "failed", finishedAt: new Date(), error: error.slice(0, 1_000) }).where(eq(jobRuns.id, id)); }
  private async getAccessContext(userId: string, type: "movie" | "series") { const integration = await this.getIntegration(); if (!integration) return undefined; const config = integration.configuration as unknown as M3uEditorConfiguration; const allowedLibraries = type === "movie" ? config.movieLibraryIds : config.seriesLibraryIds; if (!allowedLibraries?.length) return undefined; const [access] = await db.select({ id: userLibraryAccess.id }).from(userLibraryAccess).where(and(eq(userLibraryAccess.userId, userId), eq(userLibraryAccess.accessible, true), inArray(userLibraryAccess.libraryId, allowedLibraries))).limit(1); return access ? { integration, config } : undefined; }
}
export const m3uEditorRepository = new M3uEditorRepository();
function importJobName(type: "movie" | "series", tmdbId: number) { return `strm-jellyfin-import:${type}:${tmdbId}`; }
